### ISSUE TITLE
Fails to mute if you close YouTube tabs

### ISSUE THREAD

**Issue by markifi** [jasmeeto/auto-ad-mute#1]
When I normally navigate with clicking on the site or going back with the browser, it works flawlessly.
When I close a video, open another YouTube video in a different tab, it fails to mute anything.

**Comment by jasmeeto** [comment]
Hey markifi. It seems like its a problem with youtubes page loading. I've updated the code with a fix and published the new addon. It should be available within a few hours. The new code now uses tab muting rather than muting the video.

**Comment by jasmeeto** [comment]
let me know if you have any problems

**Comment by jasmeeto** [comment]
its published now, feel free to test

**Comment by markifi** [comment]
That seems to have fixed it! I've tested with maybe 50 tabs, and it's much better. Thank you!
